"""Structured activity-flow definitions for the Trip Management use cases."""

USE_CASES: list[dict] = [
    {
        "id": "UC200",
        "name": "Create Trip",
        "lanes": ["User", "System"],
        "main_steps": [
            "select Create Trip",
            "display form",
            "call UC207",
            "optionally call UC208",
            "preview",
            "select Save",
            "validate",
            "decision valid",
            "save and display trip",
        ],
        "decisions": ["valid"],
        "alternate_flows": [
            {"id": "A1", "steps": ["returns invalid information to detail entry"]},
            {"id": "A2", "steps": ["reports save failure and offers retry"]},
        ],
        "references": ["UC207 Enter Trip Details", "UC208 Update Cover Photo"],
    },
    {
        "id": "UC201",
        "name": "Edit Trip Details",
        "lanes": ["User", "System"],
        "main_steps": [
            "select Edit",
            "display existing details",
            "call UC207",
            "optionally call UC208",
            "preview",
            "select Save",
            "validate title, overlap and journal-entry date coverage",
            "save and display updated trip",
        ],
        "decisions": ["valid title, overlap and journal-entry date coverage"],
        "alternate_flows": [
            {"id": "A1", "steps": ["returns invalid changes to editing"]},
            {"id": "A2", "steps": ["retains previous information and reports failure"]},
        ],
        "references": ["UC207 Enter Trip Details", "UC208 Update Cover Photo"],
    },
    {
        "id": "UC202",
        "name": "View Trip List",
        "lanes": ["User", "System"],
        "main_steps": [
            "open Home",
            "retrieve active owned trips",
            "decision trips available",
            "display cards",
            "browse",
            "select trip",
            "call UC203",
        ],
        "decisions": ["trips available"],
        "alternate_flows": [
            {"id": "A1", "steps": ["displays empty state and Create Trip option"]},
            {"id": "A2", "steps": ["displays load error and Retry"]},
        ],
        "references": ["UC203 View Trip Details"],
    },
    {
        "id": "UC203",
        "name": "View Trip Details",
        "lanes": ["User", "System"],
        "main_steps": [
            "select trip",
            "retrieve owned active trip",
            "decision accessible",
            "display details and actions",
            "select optional action",
            "open selected function",
        ],
        "decisions": ["accessible"],
        "alternate_flows": [
            {"id": "A1", "steps": ["reports inaccessible trip"]},
            {"id": "A2", "steps": ["offers Retry or Return to List"]},
        ],
        "references": [],
    },
    {
        "id": "UC204",
        "name": "Move Trip to Trash",
        "lanes": ["User", "System"],
        "main_steps": [
            "select Move to Trash",
            "show confirmation",
            "decision confirmed",
            "move trip and related entries to recoverable Trash",
            "remove from active and Community lists",
            "refresh list",
        ],
        "decisions": ["confirmed"],
        "alternate_flows": [
            {"id": "A1", "steps": ["closes confirmation without changes"]},
            {"id": "A2", "steps": ["reports move failure"]},
        ],
        "references": [],
    },
    {
        "id": "UC205",
        "name": "View Trip Trash",
        "lanes": ["User", "System"],
        "main_steps": [
            "open Trip Trash",
            "retrieve owned recoverable trips",
            "decision data loaded",
            "decision trips available",
            "display trips and remaining recovery period",
            "decision recovery period expired",
            "select Restore",
            "call UC213",
        ],
        "decisions": ["data loaded", "trips available", "recovery period expired"],
        "alternate_flows": [
            {"id": "A1", "steps": ["displays empty state"]},
            {"id": "A2", "steps": ["displays load error and Retry"]},
            {
                "id": "A3",
                "steps": [
                    "expired items show recovery-period message and cannot start restoration",
                ],
            },
        ],
        "references": ["UC213 Restore Trip"],
    },
    {
        "id": "UC206",
        "name": "Browse Community Trips",
        "lanes": ["User", "System"],
        "main_steps": [
            "open Community",
            "retrieve public non-trashed trips",
            "decision data loaded",
            "decision trips available or match search",
            "display public cards",
            "browse or search",
            "select trip",
            "call UC214",
        ],
        "decisions": ["data loaded", "trips available or match search"],
        "alternate_flows": [
            {"id": "A1", "steps": ["displays empty state or no matches"]},
            {"id": "A2", "steps": ["displays load error and Retry"]},
        ],
        "references": ["UC214 View Community Trip Details"],
    },
    {
        "id": "UC207",
        "name": "Enter Trip Details",
        "lanes": ["User", "System"],
        "main_steps": [
            "enter title and destination",
            "accept input",
            "select start and end dates",
            "display range",
            "proceed to Save",
            "validate required fields, title length and date order",
            "decision valid",
            "return valid details to UC200 or UC201",
        ],
        "decisions": ["valid"],
        "alternate_flows": [
            {"id": "A1", "steps": ["identifies invalid field and returns to correction"]},
        ],
        "references": ["UC200 Create Trip", "UC201 Edit Trip Details"],
    },
    {
        "id": "UC208",
        "name": "Update Cover Photo",
        "lanes": ["User", "System"],
        "main_steps": [
            "select cover option",
            "display photo sources",
            "decision selection completed",
            "select or capture supported image",
            "preview",
            "save parent form",
            "decision storage successful",
            "associate cover with trip",
        ],
        "decisions": ["selection completed", "storage successful"],
        "alternate_flows": [
            {"id": "A1", "steps": ["keeps the existing cover or no cover"]},
            {"id": "A2", "steps": ["reports update failure and retains the previous cover"]},
        ],
        "references": [],
    },
    {
        "id": "UC209",
        "name": "Search or Filter Trip",
        "lanes": ["User", "System"],
        "main_steps": [
            "open search/filter controls",
            "display controls",
            "enter title/destination or select status",
            "apply criteria",
            "decision matches found",
            "display matching trips",
            "browse results",
        ],
        "decisions": ["matches found"],
        "alternate_flows": [
            {"id": "A1", "steps": ["displays no-results message and Clear option"]},
            {"id": "A2", "steps": ["clears criteria and restores the active list"]},
        ],
        "references": [],
    },
    {
        "id": "UC210",
        "name": "Publish Trip",
        "lanes": ["User", "System"],
        "main_steps": [
            "select Publish to Community",
            "show confirmation",
            "decision confirmed",
            "verify owner, private status and non-trashed state",
            "decision publish successful",
            "mark public and record publisher",
            "include in Community",
            "display Public status",
        ],
        "decisions": ["confirmed", "publish successful"],
        "alternate_flows": [
            {"id": "A1", "steps": ["keeps trip private"]},
            {"id": "A2", "steps": ["reports publication failure"]},
        ],
        "references": [],
    },
    {
        "id": "UC211",
        "name": "Unpublish Trip",
        "lanes": ["User", "System"],
        "main_steps": [
            "select Unpublish",
            "process request",
            "decision successful",
            "mark private",
            "remove from Community",
            "remove Public indicator",
            "confirm change",
        ],
        "decisions": ["successful"],
        "alternate_flows": [
            {"id": "A1", "steps": ["keeps trip public and reports failure"]},
        ],
        "references": [],
    },
    {
        "id": "UC212",
        "name": "Share Published Trip Link",
        "lanes": ["User", "System", "External Sharing Application"],
        "main_steps": [
            "select Share Link",
            "verify trip is public and sharing service exists",
            "prepare title and Trip ID message",
            "open sharing interface",
            "decision user selects target",
            "transfer message to external application",
            "user completes sharing",
            "external application handles delivery",
        ],
        "decisions": ["user selects target"],
        "alternate_flows": [
            {"id": "A1", "steps": ["closes sharing without changes"]},
            {"id": "A2", "steps": ["reports unavailable sharing service"]},
        ],
        "references": [],
    },
    {
        "id": "UC213",
        "name": "Restore Trip",
        "lanes": ["User", "System"],
        "main_steps": [
            "select Restore",
            "display confirmation",
            "decision confirmed",
            "check recovery period",
            "decision not expired",
            "check date overlap",
            "decision no conflict",
            "restore trip and journal entries",
            "remove from Trash",
            "refresh list",
        ],
        "decisions": ["confirmed", "not expired", "no conflict"],
        "alternate_flows": [
            {"id": "A1", "steps": ["reports expired recovery period and prevents restoration"]},
            {
                "id": "A2",
                "steps": [
                    "requests different dates and routes to date editing before restoration can be retried",
                ],
            },
        ],
        "references": [],
    },
    {
        "id": "UC214",
        "name": "View Community Trip Details",
        "lanes": ["User", "System"],
        "main_steps": [
            "select Community trip",
            "retrieve latest public information",
            "decision still public and found",
            "decision load successful",
            "display title, destination, dates, cover, publisher and shared content",
            "review",
            "optionally select Share",
            "call UC212",
        ],
        "decisions": ["still public and found", "load successful"],
        "alternate_flows": [
            {"id": "A1", "steps": ["reports unavailable trip and returns to Community"]},
            {"id": "A2", "steps": ["offers Retry"]},
        ],
        "references": ["UC212 Share Published Trip Link"],
    },
]
